### PR TITLE
unify build dir for Python and Java

### PR DESCRIPTION
**Pull request by songqing**
## What do these changes do?

As Ray supports Java API now, the build dir may need to be unified, so we can just build Ray once and support Python and Java API simultaneously.

Now, Python's build dir is “ray/python/ray/core”, while Java's build dir is "ray/build", so I change Python's build dir to "ray/build" too. When building for Python, just move the generated libraries and executables of Ray to Python's original dir, so it will make no difference.

### CODE REVIEW

**Comment by songqing** [comment]
@raulchen @imzhenyu @eric-jj please help to review.

**Comment by e-jinjiang** [comment]
LGTM

**Comment by songqing** [comment]
image

@raulchen I changed python's build dir to "ray/build", after building for python  completed, then I try to build for Java and come across this error. It seems some of the ray source code should be built again, so it can produce the jars which java api depended on.

**Comment by raulchen** [comment]
@songqing that's true. Python and Java do depend on different sets of binaries. 

I forgot to mention that, we need to make sure that if the user only want to build python version, we don't use anything related to JDK.

**Comment by raulchen** [comment]
LGTM, feel free to file this RP to ray whenever you think it's ready.

**Pull request merged**
